// src/contexts/LanguageContext.jsx

import React, { createContext, useContext, useState } from "react";

export const LanguageContext = createContext();

const messages = {
  ru: { 
    home: "Главная", 
    profile: "Профиль",
    patientProfile: "Профиль пациента",
    pressure: "Артериальное давление",
    pressureLastUpdated: "Последнее изменение",
    save: "Сохранить",
    edit: "Изменить",
    age: "Возраст",
    weight: "Вес",
    height: "Рост",
    diabetes: "Инсулинозависимость",
    allergy: "Аллергии",
    uploadAllergy: "Загрузить аллергенный список (CSV)", 
    allergyNotUploaded: "Аллергии не загружены.", 
    modalwindow: "График анализа - ",
    loginPatient: "Авторизация пациента",
    namePatient: "Имя пациента",
    age: "Возраст",
    weight: "Вес (кг)", 
    height: "Рост (см)", 
    iin: "ИИН",
    diabetes: "Инсулинозависимость",
    bloodGroup: "Группа крови (A, B, AB, O)", 
    rhFactor: "Резус-фактор (+/-)", 
    yes: "Да",
    no: "Нет",
    login: "Войти",
    home: "Главная",
    profile: "Профиль",
    homeHeader: "Результат анализов",
    bloodtype: "Группа крови",
    rh: "Резус-фактор",
    close: "Закрыть",
    upload: "Загрузить CSV с анализами",
    filterHeader: "Фильтрация анализов",
    allAnalyses: "Все анализы",
    applyFilter: "Применить фильтрацию",
    date: "Дата",
  },
  en: {
    home: "Home",
    profile: "Profile",
    patientProfile: "Patient Profile",
    pressure: "Blood Pressure",
    pressureLastUpdated: "Last updated",
    save: "Save",
    edit: "Edit",
    age: "Age",
    weight: "Weight",
    height: "Height",
    diabetes: "Diabetes",
    allergy: "Allergies",
    uploadAllergy: "Upload allergy CSV",
    allergyNotUploaded: "Allergies not uploaded.", 
    modalwindow: "Analysis Chart - ",
    loginPatient: "Patient Login",
    namePatient: "Patient Name",
    age: "Age",
    weight: "Weight (kg)", 
    height: "Height (cm)", 
    iin: "IIN",
    diabetes: "Diabetes",
    bloodGroup: "Blood Type (A, B, AB, O)", 
    rhFactor: "Rhesus Factor (+/-)", 
    yes: "Yes",
    no: "No",
    login: "Login",
    home: "Home",
    profile: "Profile",
    homeHeader: "Analysis results",
    bloodtype: "Blood Type",
    rh: "Rhesus Factor",
    close: "Close",
    upload: "Upload CSV with analyses",
    filterHeader: "Analysis Filter",
    allAnalyses: "All Analyses",
    applyFilter: "Apply Filter",
    date: "Date",
  },
  kz: {
    home: "Басты бет",
    profile: "Салақ парақшасы",
    patientProfile: "Науқастың профілі",
    pressure: "Қан қысымы",
    pressureLastUpdated: "Соңғы өзгеріс",
    save: "Сақтау",
    edit: "Өңдеу",
    age: "Жасы",
    weight: "Салмағы",
    height: "Бойы",
    diabetes: "Инсулинге тәуелділік",
    allergy: "Аллергиялар",
    uploadAllergy: "Аллерген тізімін жүктеу (CSV)", 
    allergyNotUploaded: "Аллергиялар жоқ.", 
    modalwindow: "Талдау графигі - ",
    loginPatient: "Науқастың кіруі",
    namePatient: "Науқастың аты-жөні",
    age: "Жасы",
    weight: "Салмағы (кг)", 
    height: "Бойы (см)", 
    iin: "ЖСН",
    diabetes: "Инсулинге тәуелділік",
    bloodGroup: "Қан тобы (A, B, AB, O)", 
    rhFactor: "Резус фактор (+/-)", 
    yes: "Иә",
    no: "Жоқ",
    login: "Кіру",
    home: "Басты бет",
    profile: "Салақ парақшасы",
    homeHeader: "Сараптама нәтижелері",
    bloodtype: "Қан тобы",
    rh: "Резус-фактор",
    close: "Жабу",
    upload: "Сараптама файлын жүктеу (CSV)", 
    filterHeader: "Сараптамаларды сүзгілеу",
    allAnalyses: "Барлық сараптамалар",
    applyFilter: "Сүзгіді қолдану",
    date: "Уақыты",
  },
};

export const LanguageProvider =({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState("ru");

  return (
    <LanguageContext.Provider
      value={{ messages: messages[currentLanguage], currentLanguage, setCurrentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
